security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /accounts
  port: 6000

feign:
  hystrix:
    enabled: true
  client.config.default:
    connectTimeout: 160000000
    readTimeout: 160000000

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://account-db:5432/${DB}
    username: nikita
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  boot.admin.client:
    instance.metadata.user:
      name: ${spring.application.name}
      password: ${ACCOUNT_SERVICE_PASSWORD}
