logging.level:
  org.springframework.security: INFO

mq:
  user: nikita
  pass: ${MQ_PASSWORD:password}
  server:
    host: activemq
    port: ${MQ_PORT:61616}
    stomp-port: 61613
  url: tcp://${mq.server.host}:${mq.server.port}


hystrix:
  metrics.enabled: true
  enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 20000
  ConnectTimeout: 20000

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

spring:
  jackson:
    deserialization:
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
      FAIL_ON_UNKNOWN_PROPERTIES: false
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  boot.admin.client:
#    username: admin
#    password: admin-password
    url: http://registry:8761/admin
#  rabbitmq:
#    host: rabbitmq

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

management:
  endpoint:
    hystrix.stream.enabled: true
    health:
      show-details: ALWAYS
      enabled: true
  endpoints:
    jmx:
      exposure.include: "*"
    web:
      exposure.include: "*"
      base-path: /actuator
      cors.allowed-origins: true
