security:
  oauth2:
    client:
      clientId: excel-service
      clientSecret: ${EXCEL_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  activemq:
    user: ${mq.user}
    password: ${mq.pass}
    in-memory: false
    broker-url: ${mq.url}
  boot.admin.client:
    instance.metadata.user:
      name: ${spring.application.name}
      password: ${EXCEL_SERVICE_PASSWORD}

info:
  component: excel-service

server:
  servlet:
    context-path: /excel
  port: 8000

feign:
  hystrix:
    enabled: true
  client.config.default:
    connectTimeout: 160000000
    readTimeout: 160000000
    loggerLevel: FULL
