security:
  oauth2:
    client:
      clientId: ship-service
      clientSecret: ${SHIP_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /ship
  port: 7000

info:
  component: ship-service

spring:
  main:
    allow-bean-definition-overriding: true
  activemq:
    user: ${mq.user}
    password: ${mq.pass}
    in-memory: false
    broker-url: ${mq.url}
  datasource:
    url: jdbc:postgresql://ship-db:5432/${DB}
    username: nikita
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          batch_size: 40
        order_inserts: true
        order_updates: true
  boot.admin.client:
    instance.metadata.user:
      name: ${spring.application.name}
      password: ${SHIP_SERVICE_PASSWORD}

feign:
  hystrix:
    enabled: true
  client.config.default:
    connectTimeout: 160000000
    readTimeout: 160000000


logging:
  level:
    org.hibernate:
      SQL: DEBUG
  # persister.entity: ERROR
